spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka

